#Ansible Playbook to run Tomcat
---
- name: Deploy to Tomcat
  hosts: tomcat
  become: yes
  become_user: ec2-user
  tasks:
    - name: Deploy WAR file
      ansible.builtin.copy:
        src: ./target/my-app-1.0-SNAPSHOT.jar
        dest: /usr/src/app/simple.jar
#     - name: Copy executable to Tomcat container
#       shell: "docker cp simple.war tomcat:/usr/local/tomcat/webapps"
    - name: Restart Container
      shell: "docker restart tomcat"
